const getConnection = require('./db');

async function createTable() {
  const connection = await getConnection();
  await connection.execute(`
    CREATE TABLE pendapatan_daerah (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama_daerah VARCHAR2(100),
      tahun NUMBER,
      pajak NUMBER,
      retribusi NUMBER,
      lain_lain NUMBER
    )
  `);
  console.log("Tabel pendapatan_daerah berhasil dibuat!");
  await connection.close();
}

createTable();
